name: push
on: 
  push:
    branches:
      - "*"
    tags-ignore:
      - "v*.*.*"
env:
  BUILD_IMAGE: bedasoftware/fhir-sdc
  CACHE_IMAGE: bedasoftware/fhir-sdc:latest
jobs:
  BuildAndTest:
    uses: ./.github/workflows/build-and-test.yml
    secrets:
      tests_aidbox_license: ${{ secrets.TESTS_AIDBOX_LICENSE }}
