name: release
on: 
  push:
    tags: 
      - "v*.*.*"
env:
  BUILD_IMAGE: bedasoftware/fhir-sdc
  CACHE_IMAGE: bedasoftware/fhir-sdc:latest
jobs:
  BuildAndTest:
    uses: ./.github/workflows/build-and-test.yml
    secrets:
      tests_aidbox_license: ${{ secrets.TESTS_AIDBOX_LICENSE }}
  Release:
    runs-on: ubuntu-latest
    needs: [BuildAndTest]
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}
      - uses: actions/checkout@v2
      - run: docker pull ${{ env.CACHE_IMAGE }} || true
      - name: Extract branch name
        shell: bash
        run: echo "branch=$(echo ${GITHUB_REF#refs/tags/v})" >>$GITHUB_OUTPUT
        id: extract_branch
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
      - run: docker run --rm --privileged tonistiigi/binfmt --install all
      - run: >-
          docker buildx build --platform linux/arm64,linux/amd64
          --cache-from ${{ env.CACHE_IMAGE }} --push
          --tag ${{ env.BUILD_IMAGE }}:${{ steps.extract_branch.outputs.branch }} --tag ${{ env.CACHE_IMAGE }} .
